settings:
  name: E-Series
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    # Remove this comment and uncomment the harmony_enabled line immediately before initial publishing
    # harmony_enabled: true
sidebar:
  entries:
    - title: E-Series docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Discover your E-Series systems
          url: /task-discover-e-series.html
    - title: Manage E-Series clusters
      entries:
        - title: View your E-Series systems
          url: /task-view-e-series.html
        - title: Remove E-Series
          url: /task-remove-e-series.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Cloud Manager
  repo: cloud-manager-family
  sidebar_label: All Cloud Manager documentation
homepage:
  tiles:
    - title: Get started
      links:
        - title: Discover your E-Series systems
          url: /task-discover-e-series.html
    - title: Manage E-Series systems
      links:
        - title: View your E-Series systems
          url: /task-view-e-series.html
        - title: Remove E-Series
          url: /task-remove-e-series.html
    - title: More information
      links:
        - title: E-Series documentation for management outside of Cloud Manager
          url: https://docs.netapp.com/us-en/e-series-family/
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
